"use client";
import {useEffect,useMemo,useState} from "react";
import {CURRICULUM,LEARNING_MODES,getCurriculumClass,type CurriculumSubject,type LearningMode} from "./curriculum-data";
import "./course-explorer.css";

type Progress=Record<string,boolean>;
const progressKey="vision-ai-course-progress-v1",selectionKey="vision-ai-course-selection-v1";

export default function CourseExplorer(){
 const [grade,setGrade]=useState<number|null>(null),[pathway,setPathway]=useState("core"),[subject,setSubject]=useState<CurriculumSubject|null>(null),[mode,setMode]=useState<LearningMode|null>(null),[progress,setProgress]=useState<Progress>({}),[query,setQuery]=useState(""),[showClasses,setShowClasses]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(selectionKey)??"null");if(saved?.grade){setGrade(saved.grade);setPathway(saved.pathway??"core")}setProgress(JSON.parse(localStorage.getItem(progressKey)??"{}"))}catch{}},[]);
 useEffect(()=>{if(grade)try{localStorage.setItem(selectionKey,JSON.stringify({grade,pathway}))}catch{}},[grade,pathway]);
 const selectedClass=grade?getCurriculumClass(grade):null,selectedPath=selectedClass?.pathways.find(x=>x.id===pathway)??selectedClass?.pathways[0];
 const subjects=useMemo(()=>selectedPath?.subjects.filter(x=>`${x.name} ${x.topics.join(" ")}`.toLowerCase().includes(query.toLowerCase()))??[],[selectedPath,query]);
 const total=(selectedPath?.subjects.length??0)*3,done=selectedPath?.subjects.reduce((n,x)=>n+LEARNING_MODES.filter(m=>progress[`${grade}-${selectedPath.id}-${x.id}-${m.mode}`]).length,0)??0;
 const chooseGrade=(next:number)=>{const c=getCurriculumClass(next);setGrade(next);setPathway(c.pathways[0].id);setSubject(null);setMode(null);setShowClasses(false)};
 const toggle=()=>{if(!grade||!selectedPath||!subject||!mode)return;const key=`${grade}-${selectedPath.id}-${subject.id}-${mode}`;setProgress(old=>{const next={...old,[key]:!old[key]};try{localStorage.setItem(progressKey,JSON.stringify(next))}catch{}return next})};
 if(!grade)return <section className="course-entry" id="courses"><div><span>YOUR PERSONAL LEARNING SPACE</span><h2>Which class are you in?</h2><p>Choose once. Switch any time; your progress stays on this device.</p></div><div className="class-picker">{CURRICULUM.map(x=><button key={x.grade} onClick={()=>chooseGrade(x.grade)}><small>{x.stage}</small><b>{x.grade}</b><span>Class {x.grade}</span></button>)}</div><p className="curriculum-note">CBSE/NCERT-aligned · English and Hindi support · Explore without sign-up</p></section>;
 if(subject&&mode&&selectedPath)return <CourseWorkspace grade={grade} pathway={selectedPath.name} subject={subject} mode={mode} complete={!!progress[`${grade}-${selectedPath.id}-${subject.id}-${mode}`]} onComplete={toggle} onBack={()=>setMode(null)} onExit={()=>{setSubject(null);setMode(null)}}/>;
 return <section className="course-dashboard" id="courses"><header><div><button className="class-switch" onClick={()=>setShowClasses(!showClasses)}>CLASS {grade}⌄</button><span>{selectedClass?.stage} stage</span><h2>Your courses</h2><p>{selectedPath?.description}</p></div><div className="course-progress"><b>{done}<small>/{total}</small></b><span>activities completed</span><i><em style={{width:`${total?done/total*100:0}%`}}/></i></div></header>
 <div className={`compact-class-picker ${showClasses?"open":""}`}>{CURRICULUM.map(x=><button className={x.grade===grade?"active":""} key={x.grade} onClick={()=>chooseGrade(x.grade)}>{x.grade}</button>)}</div>
 {(selectedClass?.pathways.length??0)>1&&<div className="pathway-tabs">{selectedClass?.pathways.map(x=><button className={x.id===selectedPath?.id?"active":""} key={x.id} onClick={()=>{setPathway(x.id);setSubject(null);setMode(null)}}><b>{x.name}</b><span>{x.description}</span></button>)}</div>}
 <label className="course-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subjects or topics"/></label>
 <div className="subject-grid">{subjects.map(x=>{const completed=LEARNING_MODES.filter(m=>progress[`${grade}-${selectedPath?.id}-${x.id}-${m.mode}`]).length;return <article style={{"--subject":x.accent} as React.CSSProperties} key={x.id}><div className="subject-icon">{x.icon}</div><small>CLASS {grade} · {completed}/3 COMPLETE</small><h3>{x.name}</h3><p>{x.topics.join(" · ")}</p><div className="subject-meter"><i style={{width:`${completed/3*100}%`}}/></div><button onClick={()=>setSubject(x)}>OPEN SUBJECT <span>→</span></button></article>})}</div>
 {subject&&<div className="activity-drawer" role="dialog" aria-modal="true"><button className="drawer-close" onClick={()=>setSubject(null)}>×</button><span>CLASS {grade} · {selectedPath?.name}</span><h3>{subject.name}</h3><p>{subject.note}</p><div>{LEARNING_MODES.map((x,i)=>{const complete=!!progress[`${grade}-${selectedPath?.id}-${subject.id}-${x.mode}`];return <button className="activity-choice" key={x.mode} onClick={()=>setMode(x.mode)}><i>{complete?"✓":x.icon}</i><span><small>{x.mode} · TOPIC {i+1}</small><b>{x.label}</b><em>{subject.topics[i]}</em></span><strong>→</strong></button>})}</div></div>}
 </section>;
}

function CourseWorkspace({grade,pathway,subject,mode,complete,onComplete,onBack,onExit}:{grade:number;pathway:string;subject:CurriculumSubject;mode:LearningMode;complete:boolean;onComplete:()=>void;onBack:()=>void;onExit:()=>void}){
 const index=LEARNING_MODES.findIndex(x=>x.mode===mode),current=LEARNING_MODES[index],topic=subject.topics[index];const [step,setStep]=useState(0),[answer,setAnswer]=useState<number|null>(null);
 const steps=mode==="Learn"?["Activate what you know",`Explore: ${topic}`,"Connect it to a new example"]:mode==="Practice"?["Predict the result",`Try: ${topic}`,"Explain the pattern"]:["Recall without hints",`Solve: ${topic}`,"Review and correct"];
 return <div className="course-workspace" role="dialog" aria-modal="true"><header><button onClick={onBack}>← SUBJECT</button><div><small>CLASS {grade} · {pathway} · {subject.name}</small><b>{current.label}</b></div><button onClick={onExit}>EXIT ×</button></header><main><aside><span style={{background:subject.accent}}>{subject.icon}</span><small>{mode}</small><h2>{topic}</h2><p>{current.description}</p><nav>{steps.map((x,i)=><button className={step===i?"active":step>i?"done":""} key={x} onClick={()=>setStep(i)}><i>{step>i?"✓":i+1}</i>{x}</button>)}</nav></aside><section className="lesson-stage"><div>STEP {step+1} OF 3</div><h3>{steps[step]}</h3>{step===0?<><p>Before seeing the explanation, say or write one thing you already know about <b>{topic}</b>.</p><article><b>THINK · PAIR · SHARE</b><p>Where might you notice this idea at home, in school, in nature or in the news?</p></article></>:step===1?<><p>Study the relationship in small pieces. Focus on what changes and why—not only the definition.</p><div className="concept-map"><span>OBSERVE<b>{topic}</b></span><i>→</i><span>REASON<b>What changes—and why?</b></span><i>→</i><span>APPLY<b>Use it in a new situation</b></span></div><article><b>AI STUDY COACH</b><p>Hints use the selected class and topic context. Camera AI remains on-device, reducing shared-server demand.</p></article></>:<><p>Choose the strongest learning strategy for this topic.</p><div className="workspace-options">{["Explain it using an example","Memorise only the heading","Skip mistakes"].map((x,i)=><button className={answer===i?(i===0?"correct":"wrong"):""} key={x} onClick={()=>setAnswer(i)}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div>{answer!==null&&<article><b>{answer===0?"STRONG CHOICE":"TRY AGAIN"}</b><p>{answer===0?"Examples reveal real understanding.":"Active recall and reviewing mistakes are stronger than passive memorisation."}</p></article>}</>}<footer><button disabled={!step} onClick={()=>setStep(x=>x-1)}>BACK</button>{step<2?<button onClick={()=>setStep(x=>x+1)}>CONTINUE →</button>:<button className={complete?"completed":""} onClick={onComplete}>{complete?"✓ COMPLETED":"MARK COMPLETE"}</button>}</footer></section></main></div>;
}
