export type LearningMode = "Learn" | "Practice" | "Mastery";
export interface CurriculumSubject { id:string; name:string; icon:string; accent:string; topics:[string,string,string]; note:string }
export interface CurriculumPathway { id:string; name:string; description:string; subjects:CurriculumSubject[] }
export interface CurriculumClass { grade:number; stage:string; pathways:CurriculumPathway[] }

const S=(id:string,name:string,icon:string,accent:string,topics:[string,string,string],note="Mapped to age-appropriate CBSE/NCERT learning outcomes."):CurriculumSubject=>({id,name,icon,accent,topics,note});
const M=(...topics:[string,string,string])=>S("mathematics","Mathematics","∑","#8b7cff",topics);
const E=(...topics:[string,string,string])=>S("english","English","Aa","#64dcff",topics);
const H=(...topics:[string,string,string])=>S("hindi","Hindi","अ","#ffb45e",topics);
const Sc=(...topics:[string,string,string])=>S("science","Science","⚗","#61e6a8",topics);
const So=(...topics:[string,string,string])=>S("social-science","Social Science","◎","#ff7da8",topics);
const AI=(...topics:[string,string,string])=>S("ai","AI & Computational Thinking","AI","#53e7ff",topics,"CBSE computational-thinking and AI skills with responsible-use guidance.");
const core=(grade:number,subjects:CurriculumSubject[]):CurriculumPathway=>({id:"core",name:"Core Curriculum",description:`Class ${grade} CBSE/NCERT learning path.`,subjects});

const gradeSubjects:Record<number,CurriculumSubject[]>={
1:[E("Letters, sounds and picture words","Story order and listening","Everyday speaking"),H("वर्ण और सरल शब्द","चित्र और कहानी","सरल वाक्य"),M("Numbers to 99","Shapes and patterns","Addition and subtraction"),S("world","The World Around Us","🌱","#72dda5",["Me, family and school","Plants and animals","Health, safety and seasons"])],
2:[E("Phonics and reading fluency","Story characters and sequence","Descriptions and punctuation"),H("मात्राएँ और शब्द","कहानी के पात्र","सरल लेखन"),M("Place value to 999","Operations and equal groups","Money, time and measurement"),S("world","The World Around Us","🌏","#72dda5",["Homes and helpers","Food, water and living things","Travel and care for Earth"])],
3:[E("Stories and poems","Grammar and sentences","Messages and paragraphs"),H("पठन और कविता","संज्ञा और क्रिया","अनुच्छेद लेखन"),M("Four operations","Fractions and measurement","Geometry and data"),S("world","The World Around Us","🌿","#72dda5",["Families and occupations","Living world and water","Maps and environment"]),AI("Patterns and instructions","Sorting information","Digital safety")],
4:[E("Prose and poetry","Grammar in context","Letters and compositions"),H("गद्य-पद्य पठन","व्याकरण प्रयोग","पत्र और संवाद"),M("Large numbers","Fractions and symmetry","Perimeter and data"),S("world","The World Around Us","🧭","#72dda5",["People and local government","Adaptation in living things","Maps and sustainability"]),AI("Everyday algorithms","Data and classification","Creative coding")],
5:[E("Inference and meaning","Grammar and vocabulary","Reports and letters"),H("साहित्य और बोध","शब्द-भेद","पत्र और कहानी"),M("Factors and multiples","Fractions and decimals","Area, volume and data"),S("world","The World Around Us","🌍","#72dda5",["Body, health and food","Habitats and resources","India and communities"]),AI("Decomposition and logic","Data patterns","Block coding and bias")],
6:[E("Narrative and comprehension","Grammar and editing","Notice and descriptive writing"),H("साहित्य और बोध","संज्ञा, सर्वनाम और काल","पत्र और संवाद"),M("Number systems","Fractions and algebra","Geometry and data"),Sc("Food and materials","Living organisms","Motion, light and electricity"),So("Early societies","Earth and maps","Diversity and government"),AI("Algorithms","Data and simple models","Coding and responsible AI")],
7:[E("Theme and character","Grammar transformations","Diary and story craft"),H("भाव और संदेश","शब्द-रचना और काल","पत्र और लेखन"),M("Rational numbers","Expressions and equations","Triangles and area"),Sc("Nutrition and transport","Heat, acids and change","Motion, electricity and ecosystems"),So("Medieval societies","Environment and atmosphere","Equality, markets and media"),AI("Flowcharts","Features and prediction","Coding, ethics and safety")],
8:[E("Critical reading","Advanced grammar","Article and speech"),H("साहित्य विश्लेषण","समास और वाक्य","लेख और पत्र"),M("Powers and roots","Linear equations","Mensuration and probability"),Sc("Crops and microbes","Materials and combustion","Force, sound and light"),So("Colonialism and reform","Resources and industries","Constitution and justice"),AI("AI project cycle","Data and evaluation","Fairness and privacy")],
9:[E("Beehive and Moments","Integrated grammar","Story and diary"),H("क्षितिज/स्पर्श","भाषा प्रयोग","पत्र और अनुच्छेद"),M("Numbers and polynomials","Equations and triangles","Circles and statistics"),Sc("Matter and atoms","Cells and health","Motion, force and energy"),So("Revolutions and Nazism","India: land and climate","Democracy and economics"),AI("AI project cycle","Vision, NLP and evaluation","Python and sustainable AI")],
10:[E("First Flight and Footprints","Analytical reading","Formal letter and paragraph"),H("साहित्य विश्लेषण","व्याकरण और बोध","औपचारिक लेखन"),M("Real numbers and quadratics","Geometry and trigonometry","Mensuration and probability"),Sc("Reactions and carbon","Life processes and heredity","Light and electricity"),So("Nationalism and globalisation","Resources and industries","Federalism and development"),AI("AI deployment cycle","Vision, NLP and data science","Bias and explainability")]
};

const senior=(grade:number):CurriculumPathway[]=>{
 const twelve=grade===12;
 const english=E(twelve?"Flamingo and Vistas":"Hornbill and Snapshots","Comprehension and expression","Article, speech and report");
 const ai=AI("Python and data science","Machine learning and evaluation","Responsible AI capstone");
 return [
 {id:"science",name:"Science",description:"Physics, Chemistry, Mathematics/Biology and language foundations.",subjects:[S("physics","Physics","λ","#64dcff",twelve?["Electricity and magnetism","Optics and waves","Modern physics"]:["Motion and mechanics","Rotation and gravitation","Thermodynamics and waves"]),S("chemistry","Chemistry","⚗","#61e6a8",twelve?["Solutions and kinetics","Inorganic chemistry","Organic reactions"]:["Atomic structure and bonding","Equilibrium and redox","Organic foundations"]),M(...(twelve?["Matrices and relations","Calculus","Vectors and probability"]:["Sets and trigonometry","Algebra and geometry","Limits and probability"] as [string,string,string])),S("biology","Biology","🧬","#72dda5",twelve?["Reproduction and genetics","Biotechnology","Ecology and evolution"]:["Living world","Cell and physiology","Plant and human systems"]),english,ai]},
 {id:"commerce",name:"Commerce",description:"Accounts, business, economics and quantitative decision-making.",subjects:[S("accountancy","Accountancy","₹","#ffb45e",twelve?["Partnership firms","Companies","Cash flow and ratios"]:["Accounting principles","Journal and ledger","Financial statements"]),S("business-studies","Business Studies","↗","#8b7cff",twelve?["Management principles","Business functions","Marketing and consumer protection"]:["Forms of business","Enterprises","Finance and trade"]),S("economics","Economics","⌁","#ff7da8",twelve?["National income and banking","Budget and balance of payments","Indian development"]:["Statistics","Demand and supply","Production and markets"]),M("Applied algebra","Financial mathematics","Statistics and probability"),english,ai]},
 {id:"humanities",name:"Humanities",description:"Society, institutions, people, space and ideas.",subjects:[S("history","History","⌛","#ffb45e",twelve?["Indian histories","Colonialism and nationalism","Partition and constitution"]:["Early societies","Cultural traditions","Modernisation"]),S("political-science","Political Science","⚖","#64dcff",twelve?["World politics","Indian politics","Globalisation and security"]:["Constitution and rights","Political theory","Citizenship and secularism"]),S("geography","Geography","◉","#61e6a8",twelve?["Human geography","Resources and trade","India: people and economy"]:["Earth systems","Climate and oceans","India: land and resources"]),S("sociology","Sociology","◎","#ff7da8",twelve?["Indian social structure","Culture and institutions","Global transformation"]:["Society and culture","Inequality and change","Research methods"]),english,ai]}
 ];
};

export const CURRICULUM:CurriculumClass[]=Array.from({length:12},(_,i)=>{const grade=i+1;const stage=grade<=2?"Foundational":grade<=5?"Preparatory":grade<=8?"Middle":grade<=10?"Secondary":"Senior Secondary";return {grade,stage,pathways:grade>=11?senior(grade):[core(grade,gradeSubjects[grade])]}});
export const LEARNING_MODES:{mode:LearningMode;label:string;description:string;icon:string}[]=[
 {mode:"Learn",label:"Concept Studio",description:"A concise visual lesson with examples and guided recall.",icon:"◈"},
 {mode:"Practice",label:"Interactive Practice",description:"Apply the idea through a simulation, sorting task or challenge.",icon:"⌁"},
 {mode:"Mastery",label:"Mastery Check",description:"Answer adaptive questions and review mistakes.",icon:"✓"}
];
export const getCurriculumClass=(grade:number)=>CURRICULUM.find(item=>item.grade===grade)??CURRICULUM[0];
