export type QuizCategory = "Physics" | "Chemistry" | "Biology" | "AI";
export type QuizDifficulty = "Easy" | "Medium" | "Difficult";

export interface QuizQuestion {
  id: number;
  classLevel: 9 | 10;
  category: QuizCategory;
  difficulty: QuizDifficulty;
  question: string;
  options: [string, string, string, string];
  answer: number;
  explanation: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {id:1,classLevel:9,category:"Physics",difficulty:"Easy",question:"Which quantity measures the rate of change of velocity?",options:["Speed","Acceleration","Momentum","Force"],answer:1,explanation:"Acceleration is the change in velocity divided by time."},
  {id:2,classLevel:9,category:"Physics",difficulty:"Easy",question:"What is the SI unit of force?",options:["Joule","Watt","Newton","Pascal"],answer:2,explanation:"One newton produces an acceleration of 1 m/s² in a mass of 1 kg."},
  {id:3,classLevel:9,category:"Physics",difficulty:"Medium",question:"A 2 kg object accelerates at 3 m/s². What force acts on it?",options:["1.5 N","5 N","6 N","9 N"],answer:2,explanation:"F = ma = 2 × 3 = 6 N."},
  {id:4,classLevel:9,category:"Physics",difficulty:"Medium",question:"Which statement describes Newton’s first law?",options:["Every force has a reaction","Force equals mass times acceleration","Objects resist changes in motion","Energy is always lost"],answer:2,explanation:"Inertia makes an object remain at rest or in uniform motion unless an unbalanced force acts."},
  {id:5,classLevel:9,category:"Physics",difficulty:"Difficult",question:"A 4 kg cart changes velocity from 2 m/s to 5 m/s. What is its change in momentum?",options:["3 kg m/s","7 kg m/s","12 kg m/s","20 kg m/s"],answer:2,explanation:"Δp = m(v − u) = 4(5 − 2) = 12 kg m/s."},
  {id:6,classLevel:9,category:"Physics",difficulty:"Easy",question:"Which energy increases when an object is lifted?",options:["Chemical","Gravitational potential","Sound","Nuclear"],answer:1,explanation:"Work against gravity is stored as gravitational potential energy."},
  {id:7,classLevel:9,category:"Physics",difficulty:"Medium",question:"A 5 N force moves an object 4 m in its direction. Work done is:",options:["1.25 J","9 J","20 J","25 J"],answer:2,explanation:"Work = force × displacement = 5 × 4 = 20 J."},
  {id:8,classLevel:9,category:"Physics",difficulty:"Medium",question:"What does power measure?",options:["Stored energy","Rate of doing work","Total force","Distance travelled"],answer:1,explanation:"Power is work done or energy transferred per unit time."},
  {id:9,classLevel:9,category:"Physics",difficulty:"Difficult",question:"If speed doubles, kinetic energy becomes:",options:["Half","Double","Four times","Eight times"],answer:2,explanation:"KE = ½mv², so doubling v multiplies kinetic energy by four."},
  {id:10,classLevel:10,category:"Physics",difficulty:"Easy",question:"The angle between an incident ray and the normal is called:",options:["Reflection angle","Incidence angle","Deviation angle","Mirror angle"],answer:1,explanation:"The angle of incidence is measured from the normal, not the mirror surface."},
  {id:11,classLevel:10,category:"Physics",difficulty:"Medium",question:"A ray strikes a plane mirror at 35° to the normal. Its reflection angle is:",options:["35°","55°","70°","90°"],answer:0,explanation:"The law of reflection states that incidence angle equals reflection angle."},
  {id:12,classLevel:10,category:"Physics",difficulty:"Easy",question:"Which lens corrects myopia?",options:["Convex","Concave","Cylindrical only","Bifocal only"],answer:1,explanation:"A concave lens diverges incoming rays so a myopic eye focuses them on the retina."},
  {id:13,classLevel:10,category:"Physics",difficulty:"Medium",question:"Hypermetropia usually forms a near-object image:",options:["On the cornea","In front of retina","Behind retina","On the iris"],answer:2,explanation:"In hypermetropia, the eye’s converging power is insufficient for near objects, so the image tends to form behind the retina."},
  {id:14,classLevel:10,category:"Physics",difficulty:"Easy",question:"Which equation is Ohm’s law?",options:["P = VI","V = IR","F = ma","E = mc²"],answer:1,explanation:"For an ohmic conductor at constant temperature, voltage equals current times resistance."},
  {id:15,classLevel:10,category:"Physics",difficulty:"Medium",question:"A 12 V battery is connected to a 6 Ω resistor. Current is:",options:["0.5 A","2 A","6 A","72 A"],answer:1,explanation:"I = V/R = 12/6 = 2 A."},
  {id:16,classLevel:10,category:"Physics",difficulty:"Difficult",question:"Two identical resistors connected in parallel have equivalent resistance:",options:["Twice one resistor","Equal to one resistor","Half one resistor","Zero"],answer:2,explanation:"For two equal resistors R in parallel, equivalent resistance is R/2."},
  {id:17,classLevel:9,category:"Chemistry",difficulty:"Easy",question:"Which particle determines an element’s atomic number?",options:["Neutron","Proton","Electron shell","Nucleus size"],answer:1,explanation:"Atomic number equals the number of protons in the nucleus."},
  {id:18,classLevel:9,category:"Chemistry",difficulty:"Medium",question:"An atom with 11 protons and 10 electrons has charge:",options:["+1","−1","0","+11"],answer:0,explanation:"One more proton than electrons gives a net charge of +1."},
  {id:19,classLevel:9,category:"Chemistry",difficulty:"Medium",question:"Isotopes of one element have the same number of:",options:["Neutrons","Nucleons","Protons","Shells always"],answer:2,explanation:"Isotopes share the same proton number but have different neutron numbers."},
  {id:20,classLevel:9,category:"Chemistry",difficulty:"Difficult",question:"The electronic configuration of chlorine (atomic number 17) is:",options:["2,7,8","2,8,7","8,8,1","2,8,8"],answer:1,explanation:"The first 17 electrons fill the shells as 2, 8 and 7 in the school-level model."},
  {id:21,classLevel:9,category:"Chemistry",difficulty:"Easy",question:"What is the maximum school-level capacity of the first shell?",options:["1","2","8","18"],answer:1,explanation:"The K shell holds a maximum of two electrons."},
  {id:22,classLevel:10,category:"Chemistry",difficulty:"Easy",question:"2Mg + O₂ → 2MgO is which reaction type?",options:["Combination","Decomposition","Displacement","Neutralisation"],answer:0,explanation:"Two reactants combine to form one type of product."},
  {id:23,classLevel:10,category:"Chemistry",difficulty:"Medium",question:"Zn + CuSO₄ → ZnSO₄ + Cu is a:",options:["Combination reaction","Double displacement reaction","Displacement reaction","Decomposition reaction"],answer:2,explanation:"More reactive zinc displaces copper from copper sulphate."},
  {id:24,classLevel:10,category:"Chemistry",difficulty:"Easy",question:"Acid plus base generally produces:",options:["Salt and water","Only gas","Metal and water","Only precipitate"],answer:0,explanation:"Neutralisation forms salt and water."},
  {id:25,classLevel:10,category:"Chemistry",difficulty:"Medium",question:"A solid that forms from two solutions is called a:",options:["Solvent","Precipitate","Catalyst","Vapour"],answer:1,explanation:"An insoluble solid produced in a solution reaction is a precipitate."},
  {id:26,classLevel:10,category:"Chemistry",difficulty:"Medium",question:"Carbon normally forms how many covalent bonds?",options:["1","2","3","4"],answer:3,explanation:"Carbon is tetravalent and normally forms four covalent bonds."},
  {id:27,classLevel:10,category:"Chemistry",difficulty:"Easy",question:"Which molecule contains a double carbon-carbon bond?",options:["Ethane","Ethene","Ethyne","Methane"],answer:1,explanation:"Ethene, C₂H₄, contains one C=C double bond."},
  {id:28,classLevel:10,category:"Chemistry",difficulty:"Medium",question:"The functional group in ethanol is:",options:["Carboxyl","Hydroxyl","Aldehyde","Ketone"],answer:1,explanation:"Ethanol contains the hydroxyl group, −OH."},
  {id:29,classLevel:10,category:"Chemistry",difficulty:"Difficult",question:"Members of a homologous series differ by:",options:["CH₄","CH₃","CH₂","COOH"],answer:2,explanation:"Successive homologues differ by one −CH₂− unit and 14 u in molecular mass."},
  {id:30,classLevel:10,category:"Chemistry",difficulty:"Medium",question:"The molecular formula of ethanoic acid is:",options:["C₂H₅OH","CH₃COOH","C₂H₄","CH₄"],answer:1,explanation:"Ethanoic acid contains CH₃ joined to the carboxyl group COOH."},
  {id:31,classLevel:9,category:"Biology",difficulty:"Easy",question:"Which organelle controls most cell activities?",options:["Vacuole","Nucleus","Ribosome","Cell wall"],answer:1,explanation:"The nucleus contains genetic material and controls cell activities."},
  {id:32,classLevel:9,category:"Biology",difficulty:"Easy",question:"Which structure is present in plant cells but absent in animal cells?",options:["Cell membrane","Mitochondrion","Cell wall","Cytoplasm"],answer:2,explanation:"Plant cells have a rigid cell wall outside the cell membrane."},
  {id:33,classLevel:9,category:"Biology",difficulty:"Medium",question:"Where does most aerobic respiration occur in a cell?",options:["Mitochondria","Golgi apparatus","Nucleus","Vacuole"],answer:0,explanation:"Mitochondria release usable energy through aerobic respiration."},
  {id:34,classLevel:9,category:"Biology",difficulty:"Medium",question:"Ribosomes mainly make:",options:["Lipids","Proteins","Starch","DNA"],answer:1,explanation:"Ribosomes are the sites of protein synthesis."},
  {id:35,classLevel:9,category:"Biology",difficulty:"Easy",question:"Chlorophyll is found mainly in:",options:["Nucleus","Chloroplasts","Vacuoles","Ribosomes"],answer:1,explanation:"Chloroplasts contain chlorophyll and perform photosynthesis."},
  {id:36,classLevel:9,category:"Biology",difficulty:"Medium",question:"Which joint permits movement in many directions at the shoulder?",options:["Hinge","Pivot","Ball-and-socket","Fixed"],answer:2,explanation:"The rounded head of the humerus moves inside the shoulder socket."},
  {id:37,classLevel:9,category:"Biology",difficulty:"Easy",question:"The vertebral column protects the:",options:["Heart","Spinal cord","Lungs","Kidneys only"],answer:1,explanation:"The vertebrae surround and protect the spinal cord."},
  {id:38,classLevel:9,category:"Biology",difficulty:"Medium",question:"Which lower-leg bone is larger and bears more weight?",options:["Fibula","Tibia","Radius","Ulna"],answer:1,explanation:"The tibia is the larger, weight-bearing bone of the lower leg."},
  {id:39,classLevel:10,category:"Biology",difficulty:"Easy",question:"Most nutrient absorption occurs in the:",options:["Stomach","Small intestine","Large intestine","Oesophagus"],answer:1,explanation:"Villi in the small intestine provide a large surface for absorption."},
  {id:40,classLevel:10,category:"Biology",difficulty:"Medium",question:"Bile is produced by the:",options:["Pancreas","Stomach","Liver","Small intestine"],answer:2,explanation:"The liver produces bile, which helps emulsify fats."},
  {id:41,classLevel:10,category:"Biology",difficulty:"Easy",question:"Water is absorbed mainly in the:",options:["Mouth","Oesophagus","Large intestine","Pancreas"],answer:2,explanation:"The large intestine absorbs much of the remaining water and salts."},
  {id:42,classLevel:10,category:"Biology",difficulty:"Medium",question:"Which chamber pumps oxygenated blood to the body?",options:["Right atrium","Right ventricle","Left atrium","Left ventricle"],answer:3,explanation:"The muscular left ventricle pumps blood through the aorta to the body."},
  {id:43,classLevel:10,category:"Biology",difficulty:"Medium",question:"The pulmonary artery carries:",options:["Oxygenated blood to body","Deoxygenated blood to lungs","Oxygenated blood to heart","Deoxygenated blood to body"],answer:1,explanation:"It carries deoxygenated blood from the right ventricle to the lungs."},
  {id:44,classLevel:10,category:"Biology",difficulty:"Easy",question:"Gas exchange occurs in tiny air sacs called:",options:["Bronchi","Tracheae","Alveoli","Villi"],answer:2,explanation:"Alveoli have thin walls and a rich blood supply for rapid gas exchange."},
  {id:45,classLevel:10,category:"Biology",difficulty:"Medium",question:"During inhalation, the diaphragm:",options:["Relaxes upward","Contracts downward","Does not move","Closes the trachea"],answer:1,explanation:"Its downward contraction increases chest volume and draws air in."},
  {id:46,classLevel:10,category:"Biology",difficulty:"Difficult",question:"Double circulation means blood passes through the heart:",options:["Once per complete circuit","Twice per complete circuit","Four times per breath","Only during exercise"],answer:1,explanation:"Pulmonary and systemic circuits make blood pass through the heart twice in one complete journey."},
  {id:47,classLevel:9,category:"AI",difficulty:"Easy",question:"What does a hand-landmark model output?",options:["A person’s identity","Points describing hand geometry","Real force in newtons","Thoughts and intentions"],answer:1,explanation:"It estimates landmark positions such as fingertips and joints."},
  {id:48,classLevel:9,category:"AI",difficulty:"Easy",question:"Inference is the process of:",options:["Collecting every internet image","Using a trained model on new input","Physically repairing a camera","Writing an exam answer"],answer:1,explanation:"Inference applies a trained model to a new frame to produce predictions."},
  {id:49,classLevel:9,category:"AI",difficulty:"Medium",question:"Why is a confidence threshold useful?",options:["It guarantees truth","It rejects weak predictions","It increases camera resolution","It removes all bias"],answer:1,explanation:"A threshold lets an app ignore predictions the model considers uncertain."},
  {id:50,classLevel:9,category:"AI",difficulty:"Medium",question:"Occlusion happens when:",options:["A body part is hidden from the camera","The model becomes conscious","The screen is too large","A servo moves"],answer:0,explanation:"Hidden or overlapping parts can prevent reliable landmark estimation."},
  {id:51,classLevel:9,category:"AI",difficulty:"Difficult",question:"Why hold the same gesture for several frames?",options:["To use more electricity","To reduce accidental one-frame detections","To train the model again","To identify the user"],answer:1,explanation:"Temporal stability rules smooth noisy frame-by-frame predictions."},
  {id:52,classLevel:10,category:"AI",difficulty:"Easy",question:"Which task is an ordinary simulation rather than AI?",options:["Estimating hand landmarks","Calculating F = ma from chosen inputs","Recognising a pose from video","Detecting a face mesh"],answer:1,explanation:"A fixed formula calculation is deterministic simulation; the camera landmark estimates use a trained model."},
  {id:53,classLevel:10,category:"AI",difficulty:"Medium",question:"Dataset bias can cause a model to:",options:["Work equally for every condition","Perform unevenly for underrepresented cases","Measure exact force","Ignore all lighting"],answer:1,explanation:"If training data lacks certain appearances or conditions, performance can be uneven."},
  {id:54,classLevel:10,category:"AI",difficulty:"Medium",question:"Local browser processing can improve privacy because:",options:["Video need not be uploaded to a server","The camera identifies everyone","It removes permission prompts","It guarantees anonymity everywhere"],answer:0,explanation:"On-device inference can keep live camera frames on the visitor’s computer."},
  {id:55,classLevel:10,category:"AI",difficulty:"Difficult",question:"A pose model directly detects:",options:["Bones inside the body","Estimated body landmarks","Medical diagnoses","Muscle strength"],answer:1,explanation:"The model estimates visible body joint locations; skeleton lines are an interface overlay."},
  {id:56,classLevel:10,category:"AI",difficulty:"Easy",question:"FPS stands for:",options:["Force per second","Frames per second","Focus prediction score","File processing system"],answer:1,explanation:"FPS reports how many visual frames are processed or displayed each second."},
  {id:57,classLevel:9,category:"Physics",difficulty:"Difficult",question:"Action and reaction forces act on:",options:["The same object","Different interacting objects","Only moving objects","Only rigid objects"],answer:1,explanation:"Newton’s third-law force pair acts on two different bodies."},
  {id:58,classLevel:10,category:"Physics",difficulty:"Medium",question:"Electrical power for 3 A at 6 V is:",options:["2 W","9 W","18 W","36 W"],answer:2,explanation:"P = VI = 6 × 3 = 18 W."},
  {id:59,classLevel:10,category:"Chemistry",difficulty:"Difficult",question:"Ethyne contains which carbon-carbon bond?",options:["Single","Double","Triple","Ionic"],answer:2,explanation:"Ethyne, C₂H₂, contains a C≡C triple covalent bond."},
  {id:60,classLevel:9,category:"Chemistry",difficulty:"Medium",question:"Mass number equals the total number of:",options:["Protons and neutrons","Protons and electrons","Only electrons","Only neutrons"],answer:0,explanation:"Protons and neutrons together are nucleons, and their total is the mass number."},
  {id:61,classLevel:10,category:"Biology",difficulty:"Medium",question:"Which vessel returns oxygenated blood from lungs to heart?",options:["Pulmonary artery","Pulmonary vein","Vena cava","Aorta"],answer:1,explanation:"Pulmonary veins carry oxygenated blood to the left atrium."},
  {id:62,classLevel:9,category:"Biology",difficulty:"Medium",question:"The Golgi apparatus mainly modifies and packages:",options:["Cell products","Chromosomes","Cell walls","Light"],answer:0,explanation:"Golgi stacks modify, sort and package proteins and other cell products."},
  {id:63,classLevel:10,category:"AI",difficulty:"Difficult",question:"Why should webcam inference avoid duplicate video timestamps?",options:["It prevents reprocessing the same frame","It improves lens power","It changes the dataset","It identifies the user"],answer:0,explanation:"Skipping an already processed timestamp saves computation without losing new visual information."},
  {id:64,classLevel:9,category:"Physics",difficulty:"Medium",question:"Momentum is calculated as:",options:["Mass ÷ velocity","Mass × velocity","Force × acceleration","Work ÷ time"],answer:1,explanation:"Linear momentum p equals mass m multiplied by velocity v."}
];
